#!/bin/sh

set -e

if [ ! -f /opt/homebrew/bin/brew ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ ! -d ~/dotfiles/ ]; then
    cd ~
fi

brew bundle -v --file=~/dotfiles/Brewfile

